/*---------------------------------------------------------- 
Tên nhóm: 2TVN
Lê Văn Vũ - 47.01.104.243
Nguyễn Gia Thuận - 4501104231
Từ Thế Danh - 4501104033
Trương Thế Nhật - 46.01.104.129
Cao Thị Thanh Trâm - 4501104250
LAB: 04 - NHOM
NGAY: 14/04/2023
----------------------------------------------------------*/

-- Tạo cơ sở dữ liệu
CREATE DATABASE QLSVNhom;
GO

-- Sử dụng cơ sở dữ liệu
USE QLSVNhom;
GO

-- Tạo các Table
CREATE TABLE SINHVIEN (
    MASV NVARCHAR(20) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    NGAYSINH DATETIME,
    DIACHI NVARCHAR(200),
    MALOP VARCHAR(20),
    TENDN NVARCHAR(100) NOT NULL,
    MATKHAU VARBINARY(MAX) NOT NULL
);

CREATE TABLE NHANVIEN (
    MANV VARCHAR(20) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    EMAIL VARCHAR(20),
    LUONG VARBINARY(MAX),
    TENDN NVARCHAR(100) NOT NULL,
    MATKHAU VARBINARY(MAX) NOT NULL,
	PUBKEY VARCHAR(20)
);

CREATE TABLE LOP (
    MALOP VARCHAR(20) PRIMARY KEY,
    TENLOP NVARCHAR(100) NOT NULL,
    MANV VARCHAR(20)
);

CREATE TABLE HOCPHAN (
MAHP VARCHAR(20) PRIMARY KEY,
TENHP NVARCHAR(100) NOT NULL,
SOTC INT
);

CREATE TABLE BANGDIEM (
MASV NVARCHAR(20) NOT NULL,
MAHP VARCHAR(20) NOT NULL,
DIEMTHI VARBINARY(MAX),
PRIMARY KEY (MASV, MAHP)
);

GO


-- Thiết lập các khóa ngoại
ALTER TABLE BANGDIEM ADD CONSTRAINT FK_BD_SV
    FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV);

ALTER TABLE BANGDIEM ADD CONSTRAINT FK_BD_HP
    FOREIGN KEY (MAHP) REFERENCES HOCPHAN(MAHP);

ALTER TABLE SINHVIEN ADD CONSTRAINT FK_SV_LOP
    FOREIGN KEY (MALOP) REFERENCES LOP(MALOP);

ALTER TABLE LOP ADD CONSTRAINT FK_LOP_NV
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);

GO


-- Procedure Insert NHANVIEN
CREATE PROCEDURE SP_INS_PUBLIC_ENCRYPT_NHANVIEN 
    @MANV VARCHAR(20),
    @HOTEN NVARCHAR(100),
    @EMAIL VARCHAR(20),
    @LUONG NVARCHAR(100),
	@TENDN NVARCHAR(100),
    @MK NVARCHAR(256),
	@PUBKEY VARCHAR(20)
AS
BEGIN
	INSERT INTO NHANVIEN(MANV, HOTEN, EMAIL, LUONG, TENDN, MATKHAU, PUBKEY)
	VALUES (@MANV, @HOTEN, @EMAIL, CONVERT(VARBINARY(MAX), @LUONG, 2), @TENDN, CONVERT(VARBINARY(MAX), @MK, 2), @PUBKEY)
END
GO

--TEST
USE QLSVNhom
GO
EXEC SP_INS_PUBLIC_ENCRYPT_NHANVIEN 'NV199', 'NGUYEN VAN A', 'NVA@',
'aaaaaaaa', 'NVA', 'bbbbbbbb', 'PUBPUB'
GO

-- Truy vấn nhân viên
CREATE PROCEDURE SP_SEL_PUBLIC_ENCRYPT_NHANVIEN
@MANV NVARCHAR(100),
@MK NVARCHAR(256)
AS
BEGIN
SELECT MANV, HOTEN, EMAIL, CONVERT(NVARCHAR(MAX), LUONG) AS LUONG
FROM NHANVIEN
WHERE MANV = @MANV AND MATKHAU = HASHBYTES('SHA1', @MK);
END
GO

--TEST
EXEC SP_SEL_PUBLIC_ENCRYPT_NHANVIEN 'NV01', '123456'

